apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: {{ .Release.Namespace }}
  labels:
    opendatahub.io/dashboard: 'true'
data:
  DEFAULT_BUCKET: copilot
  DEFAULT_REGION: us-east-1
