[build-system]
requires = ["setuptools, "setuptools-scm"] # Specify setuptools as a build dependency
build-backend = "setuptools.build_meta"

[project]
name = "data-governance-copilot-api"
version = "0.0.1"